version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'duegev'
      MYSQL_PASSWORD: 'duegevpassword'
      MYSQL_ROOT_PASSWORD: 'duegevpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks: 
      unicumnet: 
        ipv4_address: 172.20.0.55
volumes:
  my-db:

networks:
  unicumnet:
    name: opt_unicumnet
    external: true